"""The page "Netzwerk" (orcaone/network.py): what iw, ip and ping say, what Moonraker says of the
network, and the WebSocket between the page and a small paramiko server that answers commands as
the U1 does, beside a small stand-in for Moonraker; never a printer. Whether the printer answers
again after connecting anew is a stand-in too."""

import json
import socket
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import paramiko
import pytest
from websockets.exceptions import InvalidStatus
from websockets.sync.client import connect

from orcaone import app as app_module
from orcaone import camera, network, ssh
from orcaone.camera import CameraError
from conftest import call

# As a U1 said it on 25.09.2026, with another network name and access point.
LINK = """Connected to 02:00:00:AA:BB:CC (on wlan0)
\tSSID: Werkstatt
\tfreq: 2437
\tRX: 8311915 bytes (12572 packets)
\tTX: 11188171 bytes (14238 packets)
\tsignal: -71 dBm
\trx bitrate: 57.7 MBit/s
\ttx bitrate: 72.0 MBit/s
"""
STATION = """Station 02:00:00:aa:bb:cc (on wlan0)
\tinactive time:\t30 ms
\ttx packets:\t14238
\ttx retries:\t321
\ttx failed:\t4
\tsignal:  \t-71 dBm
\tconnected time:\t5400 seconds
"""
# `ip -j -s link` of iproute2 6.7, shortened: loopback, the WLAN, a USB-LAN adapter, CAN.
IP_LINK = json.dumps([
    {"ifname": "lo", "operstate": "UNKNOWN", "link_type": "loopback", "address": "00:00:00:00:00:00"},
    {"ifname": "wlan0", "operstate": "UP", "link_type": "ether", "address": "02:00:00:11:22:33", "carrier_changes": 4,
     "stats64": {"rx": {"bytes": 8311915, "packets": 12572, "errors": 0, "dropped": 7}, "tx": {"bytes": 11188171, "packets": 14238, "errors": 1, "dropped": 0}}},
    {"ifname": "eth0", "operstate": "UP", "link_type": "ether", "address": "fe:00:00:44:55:66",
     "stats64": {"rx": {"bytes": 2000, "packets": 20, "errors": 0, "dropped": 0}, "tx": {"bytes": 1000, "packets": 10, "errors": 0, "dropped": 0}}},
    {"ifname": "can0", "operstate": "UP", "link_type": "can"}])
SYSFS = "/sys/class/net/eth0/duplex:full\n/sys/class/net/eth0/speed:100\n"
ROUTE = json.dumps([{"dst": "default", "gateway": "10.30.40.1", "dev": "wlan0", "protocol": "dhcp"},
                    {"dst": "10.30.40.0/24", "dev": "wlan0", "scope": "link", "prefsrc": "10.30.40.174"}]) \
    + "\n@@\n# Generated by dhcpcd\nnameserver 10.30.40.1\nnameserver 1.1.1.1\n"
PING_IPUTILS = ("--- 10.30.40.1 ping statistics ---\n3 packets transmitted, 3 received, 0% packet loss, time 2003ms\n"
                "rtt min/avg/max/mdev = 1.021/3.456/7.012/2.100 ms\n")
PING_BUSYBOX = "--- 1.1.1.1 ping statistics ---\n3 packets transmitted, 2 packets received, 33% packet loss\nround-trip min/avg/max = 12.1/15.3/18.4 ms\n"
PING_NONE = "--- 1.1.1.1 ping statistics ---\n3 packets transmitted, 0 received, 100% packet loss, time 2040ms\n"
ROUTER = "ping -c 3 -W 1 10.30.40.1 2>&1; echo @@; ip -j neigh show 10.30.40.1"
# The router in the printer's ARP table: it answered; FAILED: it did not.
NEIGH_FOUND = json.dumps([{"dst": "10.30.40.1", "dev": "wlan0", "lladdr": "02:00:00:00:00:01", "state": ["STALE"]}])
NEIGH_FAILED = json.dumps([{"dst": "10.30.40.1", "dev": "wlan0", "state": ["FAILED"]}])
SCAN = """BSS 02:00:00:aa:bb:cc(on wlan0) -- associated
\tfreq: 2437
\tsignal: -71.00 dBm
\tInformation elements from Probe Response frame:
\tSSID: Werkstatt
\tRSN:\t * Version: 1
\t\t * Group cipher: CCMP
BSS 02:00:00:dd:ee:ff(on wlan0)
\tfreq: 2412
\tsignal: -58.00 dBm
\tSSID: Werkstatt
BSS 0a:00:00:00:00:01(on wlan0)
\tfreq: 2462
\tsignal: -80.00 dBm
\tSSID: \n"""


def said(link=LINK, power="off", station=STATION, ip=IP_LINK, sysfs=SYSFS):
    """What READ gives: the answers of iw, ip and /sys between the echo @@."""
    return f"{link}@@\nPower save: {power}\n@@\n{station}@@\n{ip}\n@@\n{sysfs}"


def test_what_iw_says():
    assert network.parse(said()) == {
        "connected": True, "power_save": False, "ssid": "Werkstatt", "access_point": "02:00:00:aa:bb:cc", "frequency": 2437,
        "channel": 6, "signal": -71.0, "rx_rate": 57.7, "tx_rate": 72.0, "connected_time": 5400, "tx_packets": 14238,
        "tx_retries": 321, "tx_failed": 4}
    # A driver that gives no station dump, rates with more after the number.
    values = network.parse(said(LINK.replace("72.0 MBit/s", "72.2 MBit/s MCS 7 short GI"), "on", ""))
    assert (values["tx_rate"], values["power_save"], values["connected_time"], values["tx_retries"]) == (72.2, True, None, None)
    assert network.parse(said("Not connected.\n", "on", "")) == {"connected": False, "power_save": True}
    # No iw, or no wlan0: nothing known.
    assert network.parse("sh: iw: not found\n@@\n@@\n@@\n@@\n") == {"connected": None, "power_save": None}
    assert [network.channel(f) for f in (2412, 2437, 2472, 2484, 2413, 5180, None)] == [1, 6, 13, 14, None, None, None]


def test_what_ip_says():
    assert network.links(said()) == [
        {"name": "wlan0", "state": "up", "mac": "02:00:00:11:22:33", "errors": 1, "dropped": 7, "carrier_changes": 4, "speed": None, "duplex": None},
        {"name": "eth0", "state": "up", "mac": "fe:00:00:44:55:66", "errors": 0, "dropped": 0, "carrier_changes": None, "speed": 100, "duplex": "full"}]
    # No cable: the kernel says -1; nothing useful from ip: no links.
    assert network.links(said(sysfs="/sys/class/net/eth0/speed:-1\n"))[1]["speed"] is None
    assert network.links(said(ip="kaputt")) == []
    assert network.route(ROUTE) == {"gateway": "10.30.40.1", "device": "wlan0", "dns": ["10.30.40.1", "1.1.1.1"]}
    assert network.route("\n@@\n") == {"gateway": None, "device": None, "dns": []}


def test_what_ping_and_a_scan_say():
    assert network.ping(PING_IPUTILS) == {"loss": 0.0, "ms": 3}
    assert network.ping(PING_BUSYBOX) == {"loss": 33.0, "ms": 15}
    assert network.ping(PING_NONE) == {"loss": 100.0, "ms": None}
    assert network.ping("ping: bad address") == {"loss": None, "ms": None}
    assert network.neighbour(NEIGH_FOUND) is True
    assert network.neighbour(NEIGH_FAILED) is False
    assert network.neighbour(json.dumps([{"dst": "10.30.40.1", "lladdr": "02:00:00:00:00:01", "state": "REACHABLE"}])) is True
    assert network.neighbour("") is False and network.neighbour("[]") is False and network.neighbour("{}") is False
    assert network.networks(SCAN) == [
        {"bssid": "02:00:00:dd:ee:ff", "ssid": "Werkstatt", "frequency": 2412, "channel": 1, "signal": -58.0, "associated": False},
        {"bssid": "02:00:00:aa:bb:cc", "ssid": "Werkstatt", "frequency": 2437, "channel": 6, "signal": -71.0, "associated": True},
        {"bssid": "0a:00:00:00:00:01", "ssid": "", "frequency": 2462, "channel": 11, "signal": -80.0, "associated": False}]


@pytest.fixture
def moonraker():
    """/machine/system_info with the printer's interfaces, /machine/peripherals/usb with a USB-LAN
    adapter, /server/info with Moonraker's Date, the print files and one of them."""
    body = bytes(range(256)) * 20
    asked = []
    usb = [{"usb_devices": [{"manufacturer": "Realtek", "product": "USB 10/100 LAN", "vendor_id": "0bda", "product_id": "8152",
                             "class": "Vendor Specific Class"},
                            {"manufacturer": "Linux Foundation", "product": "2.0 root hub", "vendor_id": "1d6b", "product_id": "0002",
                             "class": "Hub"}]}]

    class Handler(BaseHTTPRequestHandler):
        def do_GET(self):
            asked.append((self.path, self.headers.get("Range")))
            if self.path == "/server/info":
                return self._send(json.dumps({"result": {"klippy_state": "ready"}}).encode())
            if self.path == "/machine/system_info":
                return self._send(json.dumps({"result": {"system_info": {"network": {
                    "wlan0": {"mac_address": "02:00:00:11:22:33", "ip_addresses": [
                        {"family": "ipv4", "address": "127.0.0.1", "is_link_local": False},
                        {"family": "ipv6", "address": "fe80::1", "is_link_local": True}]},
                    "eth0": {"mac_address": "fe:00:00:44:55:66", "ip_addresses": [{"family": "ipv4", "address": "10.30.40.175", "is_link_local": False}]}}}}}).encode())
            if self.path == "/machine/peripherals/usb" and usb[0] is not None:
                return self._send(json.dumps({"result": usb[0]}).encode())
            if self.path == "/server/files/list?root=gcodes":
                return self._send(json.dumps({"result": [{"path": "klein.gcode", "size": 10},
                                                         {"path": "Groß Teil.gcode", "size": len(body)}]}).encode())
            if self.path == "/server/files/gcodes/Gro%C3%9F%20Teil.gcode":
                last = int(self.headers["Range"].split("-")[1])
                return self._send(body[:last + 1], 206)
            self._send(b"{}", 404)

        def _send(self, data, status=200):
            self.send_response(status)   # with Date, as Moonraker's Tornado sends it
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def log_message(self, *args):
            pass

    httpd = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    yield f"127.0.0.1:{httpd.server_address[1]}", asked, usb
    httpd.shutdown()


def test_what_moonraker_says_of_the_network(moonraker):
    host, _, usb = moonraker
    assert network.interfaces(host) == [
        {"name": "wlan0", "mac": "02:00:00:11:22:33", "ipv4": ["127.0.0.1"], "ipv6": [], "used": True},
        {"name": "eth0", "mac": "fe:00:00:44:55:66", "ipv4": ["10.30.40.175"], "ipv6": [], "used": False}]
    # Only the network adapter among the USB devices; no list at all on a Moonraker without one.
    assert network.usb(host) == [{"name": "Realtek USB 10/100 LAN", "id": "0bda:8152"}]
    usb[0] = None
    assert network.usb(host) is None
    found = network.answer_time(host)
    assert isinstance(found["ms"], int) and abs(found["clock"]) <= 2
    # This computer is in the printer's network (here: both on 127.0.0.1).
    assert network.computer(host) == {"address": "127.0.0.1", "same_net": True}
    assert network.computer("256.1.1.1") == {"address": None, "same_net": None}


def test_measure_reads_only_the_start_of_the_largest_file(moonraker, monkeypatch):
    host, asked, _ = moonraker
    monkeypatch.setattr(network, "LIMIT", 1000)
    found = network.measure(host)
    assert found["bytes"] == 1000 and found["down"] > 0 and isinstance(found["latency"], int)
    assert asked[-1] == ("/server/files/gcodes/Gro%C3%9F%20Teil.gcode", "bytes=0-999")
    assert sum(1 for path, _ in asked if path == "/server/info") == 5
    monkeypatch.setattr(camera, "_get", lambda host, path: [] if "list" in path else {})
    with pytest.raises(CameraError) as err:
        network.measure(host)
    assert err.value.code == "wifi_no_file"


class Printer(paramiko.ServerInterface):
    """root with the U1's password as shipped unless a test sets another; keys never fit. Answers
    each command with what outputs has for it, else nothing."""

    def __init__(self):
        self.password, self.logins, self.commands = "snapmaker", 0, []
        self.outputs = {network.READ: said(), network.ROUTE: ROUTE, network.SCAN: SCAN,
                        ROUTER: PING_IPUTILS + "@@\n[]\n", "ping -c 3 -W 1 1.1.1.1 2>&1": PING_BUSYBOX,
                        f"timeout 5 python3 -c \"import socket;print(socket.gethostbyname('{network.NAME}'))\" 2>&1": "13.248.169.48\n"}

    def check_channel_request(self, kind, chanid):
        return paramiko.OPEN_SUCCEEDED if kind == "session" else paramiko.OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED

    def get_allowed_auths(self, username):
        return "password,publickey"

    def check_auth_password(self, username, password):
        if (username, password) != ("root", self.password):
            return paramiko.AUTH_FAILED
        self.logins += 1
        return paramiko.AUTH_SUCCESSFUL

    def check_auth_publickey(self, username, key):
        return paramiko.AUTH_FAILED

    def check_channel_exec_request(self, channel, command):
        command = command.decode()
        self.commands.append(command)
        answer = self.outputs.get(command, "")

        # Output, exit status and end of output, but not closed: paramiko acknowledges the command only
        # after this returns, and a channel closed before that fails the command. The client closes it.
        def reply():
            try:
                channel.sendall(answer.encode())
                channel.send_exit_status(0)
                channel.shutdown_write()
            except (OSError, EOFError):
                pass   # the test closed the page, and so the connection, meanwhile
        threading.Thread(target=reply, daemon=True).start()
        return True


@pytest.fixture
def printer(monkeypatch, moonraker):
    """A listening SSH server as the U1 "Snapmaker U1", whose Moonraker is the stand-in above; OrcaOne's
    port 22 points to the SSH server. Quick readings, and no waits between tries."""
    key = paramiko.ECDSAKey.generate()
    listener = socket.create_server(("127.0.0.1", 0))
    monkeypatch.setattr(ssh, "PORT", listener.getsockname()[1])
    monkeypatch.setattr(network, "EVERY", 0.05)
    monkeypatch.setattr(network, "SETTLE", 0)
    monkeypatch.setattr(network, "POLL", 0.05)
    served = Printer()

    def session(conn):
        transport = paramiko.Transport(conn)
        transport.add_server_key(key)
        try:
            transport.start_server(server=served)
        except (paramiko.SSHException, EOFError):
            return
        # Channels not taken with accept() stay with the transport; one taken and dropped would close.
        while transport.is_active():
            time.sleep(0.2)

    def serve():
        while True:
            try:
                conn, _ = listener.accept()
            except OSError:
                return
            threading.Thread(target=session, args=(conn,), daemon=True).start()

    threading.Thread(target=serve, daemon=True).start()
    camera.set_host("Snapmaker U1", moonraker[0])
    yield served
    listener.close()


def _open(server, printer="Snapmaker%20U1"):
    return connect(server.replace("http://", "ws://") + f"/api/network?model={printer}", origin=server, open_timeout=5)


def _next(ws, kind, test=lambda message: True):
    """The next message of that type that passes the test."""
    end = time.monotonic() + 15
    while time.monotonic() < end:
        message = json.loads(ws.recv(timeout=max(0.01, end - time.monotonic())))
        if message["type"] == kind and test(message):
            return message
    raise AssertionError(f"no {kind}")


def _answering(monkeypatch, *answers):
    """Whether the printer answers, one after the other; then as the last one."""
    left = list(answers)
    monkeypatch.setattr(network, "_answers", lambda host: left.pop(0) if len(left) > 1 else left[0])


def _check(ws, item):
    return _next(ws, "check", lambda m: m["item"] == item and m["state"] != "running")


def test_the_page_on_a_u1(server, printer):
    """Moonraker's part first, then the login, the route and the checks, then the chip again and
    again over the one connection."""
    with _open(server) as ws:
        info = _next(ws, "info")
        assert [i["name"] for i in info["interfaces"]] == ["wlan0", "eth0"] and info["interfaces"][0]["used"]
        assert info["usb"] == [{"name": "Realtek USB 10/100 LAN", "id": "0bda:8152"}]
        assert info["computer"]["same_net"] is True
        # No key here: the password as shipped.
        assert _next(ws, "ssh") == {"type": "ssh", "state": "open", "via": "default", "keys": True, "key": None}
        assert _next(ws, "route") == {"type": "route", "gateway": "10.30.40.1", "device": "wlan0", "dns": ["10.30.40.1", "1.1.1.1"]}
        assert _check(ws, "printer")["state"] == "ok"
        assert _check(ws, "clock")["state"] == "ok"
        assert (_check(ws, "internet")["state"], _check(ws, "dns")) == (
            "warn", {"type": "check", "item": "dns", "state": "ok", "value": "13.248.169.48"})
        assert {k: v for k, v in _check(ws, "router").items() if k != "type"} == {"item": "router", "state": "ok", "loss": 0.0, "ms": 3}
        values = _next(ws, "values")
        assert (values["ssid"], values["signal"], values["channel"]) == ("Werkstatt", -71.0, 6)
        assert [(l["name"], l["speed"]) for l in values["links"]] == [("wlan0", None), ("eth0", 100)]
        assert values["time"] == pytest.approx(time.time(), abs=5)
        _next(ws, "values")
        assert printer.logins == 1
        # Again on click: route and checks; the WLANs around; nothing lost the router.
        printer.outputs["ping -c 3 -W 1 1.1.1.1 2>&1"] = PING_NONE
        ws.send(json.dumps({"do": "check"}))
        assert _check(ws, "internet")["state"] == "err"
        _check(ws, "router")
        ws.send(json.dumps({"do": "scan"}))
        networks = _next(ws, "scan")["networks"]
        assert [n["channel"] for n in networks] == [1, 6, 11] and networks[1]["associated"]
        assert printer.logins == 1


def test_a_router_that_ignores_a_ping(server, printer):
    """UniFi ignores a ping from an isolated network: the router is there all the same when the
    internet answers through it or it answered ARP; only with neither it is not."""
    printer.outputs[ROUTER] = PING_NONE + "@@\n" + NEIGH_FAILED
    with _open(server) as ws:
        found = _check(ws, "router")
        assert (found["state"], found["code"], found["ms"]) == ("ok", "no_ping", None)
        printer.outputs["ping -c 3 -W 1 1.1.1.1 2>&1"] = PING_NONE
        printer.outputs[ROUTER] = PING_NONE + "@@\n" + NEIGH_FOUND
        ws.send(json.dumps({"do": "check"}))
        assert _check(ws, "internet")["state"] == "err"
        found = _check(ws, "router")
        assert (found["state"], found["code"]) == ("ok", "no_ping")
        printer.outputs[ROUTER] = PING_NONE + "@@\n" + NEIGH_FAILED
        ws.send(json.dumps({"do": "check"}))
        found = _check(ws, "router")
        assert found["state"] == "err" and "code" not in found


def test_connect_anew_and_wait(server, printer, monkeypatch):
    # The link goes, the printer does not answer twice, then it is back.
    with _open(server) as ws:
        _check(ws, "router")
        _answering(monkeypatch, False, False, True)
        ws.send(json.dumps({"do": "reconnect"}))
        ws.send(json.dumps({"do": "reconnect"}))   # while it waits: one at a time
        assert _next(ws, "waiting")["action"] == "reconnect"
        back = _next(ws, "back")
        assert back["action"] == "reconnect" and back["seconds"] >= 0
        # Then it reads again, over a new connection, and says how it logged in (the U1 may have
        # forgotten a key at a start).
        assert _next(ws, "ssh") == {"type": "ssh", "state": "open", "via": "default", "keys": True, "key": None}
        _next(ws, "values")
        assert printer.commands.count(network.RECONNECT) == 1 and printer.logins == 2
        # Never back: after WAIT the page says so.
        monkeypatch.setitem(network.WAIT, "reconnect", 0)
        _answering(monkeypatch, False)
        ws.send(json.dumps({"do": "reconnect"}))
        assert _next(ws, "failed") == {"type": "failed", "action": "reconnect", "code": "wifi_timeout"}


def test_start_anew_only_without_a_print(server, printer, monkeypatch):
    printing = [True]
    monkeypatch.setattr(network, "_printing", lambda host: printing[0])
    with _open(server) as ws:
        _check(ws, "router")
        ws.send(json.dumps({"do": "reboot"}))
        assert _next(ws, "failed") == {"type": "failed", "action": "reboot", "code": "wifi_printing"}
        assert network.REBOOT not in printer.commands
        # Idle: it still answers, then no longer, then again.
        printing[0] = False
        _answering(monkeypatch, True, False, True)
        ws.send(json.dumps({"do": "reboot"}))
        assert _next(ws, "back")["action"] == "reboot"
        assert printer.commands.count(network.REBOOT) == 1


def test_the_printer_anew_from_the_strip(server, printer, monkeypatch):
    """The whole printer anew from the strip above the pages or the list next to the emergency stop (the user's wish of
    26.09.2026: after a restart of Klipper the U1's display kept its error): the U1 over SSH as on
    this page, never while it prints; any other Klipper printer through Moonraker."""
    printing = [True]
    monkeypatch.setattr(network, "_printing", lambda host: printing[0])
    status, body = call(f"{server}/api/printers/reboot", "POST", {"model": "Snapmaker U1"}, headers={"Origin": server})
    assert (status, json.loads(body)) == (409, {"error": "wifi_printing"})
    assert network.REBOOT not in printer.commands
    printing[0] = False
    status, body = call(f"{server}/api/printers/reboot", "POST", {"model": "Snapmaker U1"}, headers={"Origin": server})
    assert (status, json.loads(body)) == (200, {"rebooting": True})
    assert printer.commands.count(network.REBOOT) == 1
    # Another Klipper printer: Moonraker's own call, no SSH.
    sent = []
    monkeypatch.setattr(network.printer_files, "_order", lambda host, method, params, timeout=None: sent.append((host, method)) or {})
    camera.set_host("Voron", "127.0.0.1:1")
    status, body = call(f"{server}/api/printers/reboot", "POST", {"model": "Voron"}, headers={"Origin": server})
    assert (status, json.loads(body), sent) == (200, {"rebooting": True}, [("127.0.0.1:1", "machine.reboot")])
    assert printer.commands.count(network.REBOOT) == 1
    assert call(f"{server}/api/printers/reboot", "POST", {"model": "Unbekannt"}, headers={"Origin": server})[0] == 404


def test_power_saving_off_and_speed(server, printer, monkeypatch):
    printer.outputs[network.READ] = said(power="on")
    printer.outputs[f"{network.POWER_SAVE_OFF}; {network.READ}"] = said(power="off")
    monkeypatch.setattr(network, "measure", lambda host: {"latency": 12, "down": 18.5, "bytes": 4194304})
    with _open(server) as ws:
        assert _next(ws, "values")["power_save"] is True
        _check(ws, "router")
        ws.send(json.dumps({"do": "power_save_off"}))
        assert _next(ws, "values", lambda m: m["power_save"] is False)
        assert f"{network.POWER_SAVE_OFF}; {network.READ}" in printer.commands
        ws.send("kein JSON")   # ignored, the page stays
        ws.send(json.dumps({"do": "speed"}))
        assert _next(ws, "speed") == {"type": "speed", "latency": 12, "down": 18.5, "bytes": 4194304}


def test_without_ssh_what_moonraker_says(server, printer, monkeypatch):
    """Root Access off, or neither key nor password fits: the page keeps Moonraker's part and the
    printer's checks; the rest needs SSH. Any other Klipper printer: no SSH at all."""
    closed = socket.create_server(("127.0.0.1", 0))
    monkeypatch.setattr(ssh, "PORT", closed.getsockname()[1])
    closed.close()
    with _open(server) as ws:
        assert _next(ws, "info")["interfaces"]
        answer = _next(ws, "ssh")
        assert (answer["state"], answer["code"]) == ("failed", "ssh_unreachable")
        assert _check(ws, "printer")["state"] == "ok"
        assert _next(ws, "check", lambda m: m["item"] == "router")["state"] == "ssh"
        ws.send(json.dumps({"do": "scan"}))
        assert _next(ws, "failed") == {"type": "failed", "action": "scan", "code": "ssh_needed"}
    camera.set_host("MyKlipper", camera.printers()["Snapmaker U1"]["host"])
    with _open(server, "MyKlipper") as ws:
        assert _next(ws, "ssh") == {"type": "ssh", "state": "none"}
        assert _next(ws, "check", lambda m: m["item"] == "dns")["state"] == "ssh"
    with _open(server, "Unbekannt") as ws:
        assert json.loads(ws.recv(timeout=5)) == {"type": "error", "code": "printer_not_found"}
    # Hard rule 8: only OrcaOne's own page.
    with pytest.raises(InvalidStatus):
        connect(server.replace("http://", "ws://") + "/api/network?model=Snapmaker%20U1", origin="http://evil.example", open_timeout=5)


def test_no_login_says_so(server, printer):
    printer.password = "geändert"
    with _open(server) as ws:
        answer = _next(ws, "ssh")
        assert (answer["state"], answer["code"]) == ("failed", "ssh_login")


def test_from_another_device_no_keys_of_this_computer(server, printer, monkeypatch):
    """As on the page "SSH": from the LAN only the password as shipped, never this computer's keys."""
    monkeypatch.setattr(app_module, "is_remote", lambda client: True)
    tried, real = [], ssh.connect
    monkeypatch.setattr(ssh, "connect", lambda host, user, password=None, key=None: tried.append(password) or real(host, user, password, key))
    ssh.save_setting("Snapmaker U1", None, None, "auto")   # at the computer the keys would come first
    with _open(server) as ws:
        assert (_next(ws, "ssh")["keys"], _next(ws, "values") is not None) == (False, True)
    assert tried == ["snapmaker"]


def test_the_login_as_chosen(server, printer, monkeypatch):
    """As chosen on "SSH" (ssh.login_of): with nothing chosen only the password as shipped, with
    "auto" the keys first; the chosen key is said, so the page warns only when that one failed."""
    tried, real = [], ssh.connect
    monkeypatch.setattr(ssh, "connect", lambda host, user, password=None, key=None: tried.append(password) or real(host, user, password, key))
    for login, expected in ((None, ["snapmaker"]), ("auto", [None, "snapmaker"])):
        tried.clear()
        ssh.save_setting("Snapmaker U1", None, None, login)
        with _open(server) as ws:
            assert _next(ws, "ssh") == {"type": "ssh", "state": "open", "via": "default", "keys": True, "key": None}
        assert tried == expected, login


def test_one_action_at_a_time_is_said(server, printer):
    """While the first checks run, an action is refused with a word, never swallowed: the page would
    wait for it forever."""
    with _open(server) as ws:
        ws.send(json.dumps({"do": "scan"}))
        assert _next(ws, "failed") == {"type": "failed", "action": "scan", "code": "wifi_busy"}


def test_no_restart_while_nobody_knows(monkeypatch):
    """Klipper prints or not, and Moonraker cannot tell: no restart. Klipper not ready: no print."""
    def refused(host, objects):
        raise CameraError("camera_unreachable")
    monkeypatch.setattr(camera, "query", refused)
    klippy = ["ready"]
    monkeypatch.setattr(camera, "_get", lambda host, path: {"klippy_state": klippy[0]})
    with pytest.raises(CameraError) as err:
        network._printing("x")
    assert err.value.code == "wifi_printing_unknown"
    klippy[0] = "shutdown"
    assert network._printing("x") is False
    monkeypatch.setattr(camera, "_get", lambda host, path: (_ for _ in ()).throw(CameraError("camera_unreachable")))
    with pytest.raises(CameraError):
        network._printing("x")
